server:
  port: 9100
spring:
  application:
    name: online-taxi-zuul
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver1:7900/eureka/
  instance:
    hostname: localhost
    instance-id: online-taxi-zuul

zuul:
  routes:
    #此处名字随便取
    custom-zuul-name:
      path: /zuul-custom-name/**
      service-id: service-sms
  #以下配置为空表示：所有请求头都透传到后面微服务。
  sensitive-headers:
logging:
  level:
    root: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      ##默认是never
      show-details: ALWAYS
      enabled: true
    routes:
      enabled: true