server:
  port: 8080
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:7900/eureka/
spring:
  application:
    name: api-passenger
logging:
  level:
    root: info